"""add_chat_session_tables

Revision ID: 70e2fa885a1e
Revises: 001_add_users
Create Date: 2026-04-22 20:24:10.567859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e2fa885a1e'
down_revision: Union[str, None] = '001_add_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index('idx_relations_project', table_name='relations')
    op.drop_index('idx_relations_source', table_name='relations')
    op.drop_index('idx_relations_target', table_name='relations')
    op.drop_index('idx_relations_type', table_name='relations')
    op.drop_table('relations')
    op.drop_index('idx_entities_name', table_name='entities', postgresql_using='gin')
    op.drop_index('idx_entities_project', table_name='entities')
    op.drop_index('idx_entities_type', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_eval_samples_run', table_name='evaluation_samples')
    op.drop_table('evaluation_samples')
    op.drop_index('idx_eval_runs_project', table_name='evaluation_runs')
    op.drop_index('idx_eval_runs_time', table_name='evaluation_runs')
    op.drop_index('idx_eval_runs_type', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_project', table_name='audit_logs')
    op.drop_index('idx_audit_time', table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.drop_index('idx_sections_doc', table_name='doc_sections')
    op.drop_index('idx_sections_fts', table_name='doc_sections', postgresql_using='gin')
    op.drop_index('idx_sections_path', table_name='doc_sections')
    op.drop_index('idx_sections_project', table_name='doc_sections')
    op.create_index(op.f('ix_doc_sections_doc_id'), 'doc_sections', ['doc_id'], unique=False)
    op.create_index(op.f('ix_doc_sections_project_id'), 'doc_sections', ['project_id'], unique=False)
    op.drop_index('idx_structure_doc', table_name='doc_structure')
    op.drop_index('idx_structure_parent', table_name='doc_structure')
    op.create_index(op.f('ix_doc_structure_doc_id'), 'doc_structure', ['doc_id'], unique=False)
    op.drop_index('idx_docs_format', table_name='documents')
    op.drop_index('idx_docs_project', table_name='documents')
    op.drop_index('idx_docs_status', table_name='documents')
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.drop_index('idx_pm_project', table_name='project_members')
    op.drop_index('idx_pm_user', table_name='project_members')
    op.drop_constraint('project_members_project_id_user_id_key', 'project_members', type_='unique')
    op.drop_index('idx_projects_org', table_name='projects')
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.drop_index('idx_terms_org', table_name='term_glossary')
    op.drop_index('idx_terms_term', table_name='term_glossary', postgresql_using='gin')
    op.create_index(op.f('ix_term_glossary_org_id'), 'term_glossary', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_glossary_org_id'), table_name='term_glossary')
    op.create_index('idx_terms_term', 'term_glossary', ['term'], unique=False, postgresql_using='gin')
    op.create_index('idx_terms_org', 'term_glossary', ['org_id'], unique=False)
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.create_index('idx_projects_org', 'projects', ['org_id'], unique=False)
    op.create_unique_constraint('project_members_project_id_user_id_key', 'project_members', ['project_id', 'user_id'])
    op.create_index('idx_pm_user', 'project_members', ['user_id'], unique=False)
    op.create_index('idx_pm_project', 'project_members', ['project_id'], unique=False)
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.create_index('idx_docs_status', 'documents', ['conversion_status'], unique=False)
    op.create_index('idx_docs_project', 'documents', ['project_id'], unique=False)
    op.create_index('idx_docs_format', 'documents', ['source_format'], unique=False)
    op.drop_index(op.f('ix_doc_structure_doc_id'), table_name='doc_structure')
    op.create_index('idx_structure_parent', 'doc_structure', ['parent_id'], unique=False)
    op.create_index('idx_structure_doc', 'doc_structure', ['doc_id'], unique=False)
    op.drop_index(op.f('ix_doc_sections_project_id'), table_name='doc_sections')
    op.drop_index(op.f('ix_doc_sections_doc_id'), table_name='doc_sections')
    op.create_index('idx_sections_project', 'doc_sections', ['project_id'], unique=False)
    op.create_index('idx_sections_path', 'doc_sections', ['section_path'], unique=False)
    op.create_index('idx_sections_fts', 'doc_sections', ['ts_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_sections_doc', 'doc_sections', ['doc_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_project', 'audit_logs', ['project_id'], unique=False)
    op.create_index('idx_audit_event', 'audit_logs', ['event_type'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('run_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dataset_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithfulness_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('relevancy_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='evaluation_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_eval_runs_type', 'evaluation_runs', ['run_type'], unique=False)
    op.create_index('idx_eval_runs_time', 'evaluation_runs', ['created_at'], unique=False)
    op.create_index('idx_eval_runs_project', 'evaluation_runs', ['project_id'], unique=False)
    op.create_table('evaluation_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ground_truth', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('faithfulness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('relevancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name='evaluation_samples_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evaluation_samples_pkey')
    )
    op.create_index('idx_eval_samples_run', 'evaluation_samples', ['run_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name='entities_doc_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='entities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_entities_type', 'entities', ['type'], unique=False)
    op.create_index('idx_entities_project', 'entities', ['project_id'], unique=False)
    op.create_index('idx_entities_name', 'entities', ['name'], unique=False, postgresql_using='gin')
    op.create_table('relations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name='relations_source_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name='relations_target_entity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='relations_pkey')
    )
    op.create_index('idx_relations_type', 'relations', ['relation_type'], unique=False)
    op.create_index('idx_relations_target', 'relations', ['target_entity_id'], unique=False)
    op.create_index('idx_relations_source', 'relations', ['source_entity_id'], unique=False)
    op.create_index('idx_relations_project', 'relations', ['project_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
