/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description 上传文档 — 非阻塞，立即返回
         *
         *     流程:
         *     1. 验证文件格式和大小
         *     2. 计算 MD5 checksum
         *     3. 上传源文件到 MinIO（唯一的同步 I/O，通常 <1s）
         *     4. 创建 DB 记录 (status=pending)
         *     5. 派发 Celery 异步任务（转换+索引）
         *     6. 立即返回 doc_id，前端轮询 GET /documents/{doc_id} 查看状态
         *
         *     需登录；`upload_by` 可省略（默认当前用户），若填写须与 Token 用户一致。
         *
         *     如果 MinIO 或 DB 操作失败，执行回滚：
         *     - MinIO 失败 → 直接返回错误
         *     - DB 失败 → 清理已上传的 MinIO 文件
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/list/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description 列出项目中的所有文档（需为项目成员）
         */
        get: operations["list_documents_api_v1_documents_list__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description 获取单个文档详情（含转换状态）
         *     前端轮询此接口查看异步转换进度: pending → processing → completed/failed
         */
        get: operations["get_document_api_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description 删除文档及其所有索引（需编辑者或管理员）
         */
        delete: operations["delete_document_api_v1_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Markdown
         * @description 获取文档的 Markdown 内容
         */
        get: operations["get_document_markdown_api_v1_documents__doc_id__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description RAG 检索主入口（非流式）
         *
         *     完整 11 步管道:
         *     1. 查询输入  2. 术语识别  3. 查询路由
         *     4-7. 混合检索 + RRF + Reranker
         *     8. Agentic 路径判断  9. 术语注入
         *     10. 答案生成 + 引用  11. 审计日志
         */
        post: operations["search_api_v1_search__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stream
         * @description SSE 流式检索 — 实时推送检索过程和答案
         *
         *     事件类型:
         *       - step:     进度状态更新
         *       - thinking: Agentic RAG 推理思考过程
         *       - chunk:    LLM 生成的文本增量
         *       - citation: 引用来源信息
         *       - done:     完成信号 + 统计信息
         *       - error:    错误信息
         */
        get: operations["search_stream_api_v1_search_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/skill/{skill_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoke Skill
         * @description 直接调用指定 Skill
         *
         *     可用 Skills:
         *     - document_analysis: 单文档分析
         *     - cross_document_compare: 跨文档对比
         *     - project_health: 项目健康评估
         *     - report_generation: 报告生成
         */
        post: operations["invoke_skill_api_v1_search_skill__skill_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description 列出所有已注册的 Skills
         */
        get: operations["list_skills_api_v1_search_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/list_documents/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp List Documents
         * @description MCP Tool: list_documents
         *     列出项目中所有文档，Agent 先了解知识库全貌再决策
         */
        get: operations["mcp_list_documents_api_v1_mcp_list_documents__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/get_outline/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Get Outline
         * @description MCP Tool: get_document_outline
         *     获取指定文档的章节目录树，Agent 先看目录再精读
         */
        get: operations["mcp_get_outline_api_v1_mcp_get_outline__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/search_sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Search Sections
         * @description MCP Tool: search_sections
         *     按关键词在项目文档中搜索，返回匹配章节（PostgreSQL 全文检索）
         */
        get: operations["mcp_search_sections_api_v1_mcp_search_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/read_section/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Read Section
         * @description MCP Tool: read_section
         *     读取指定章节的完整 Markdown 内容，保留原始结构
         */
        get: operations["mcp_read_section_api_v1_mcp_read_section__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/entities/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entity Types
         * @description 获取项目中所有实体类型及数量
         */
        get: operations["list_entity_types_api_v1_graph_entities__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neighbors
         * @description 查找实体的邻居（1-3 度）
         */
        get: operations["get_neighbors_api_v1_graph_neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph Query
         * @description 自然语言图查询
         */
        get: operations["graph_query_api_v1_graph_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/extract/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Extraction
         * @description 手动触发单个文档的实体关系抽取
         */
        post: operations["trigger_extraction_api_v1_graph_extract__doc_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/project/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Project Graph
         * @description 删除项目的全部图数据
         */
        delete: operations["delete_project_graph_api_v1_graph_project__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Evaluation
         * @description 手动触发一次批量评估
         */
        post: operations["trigger_evaluation_api_v1_evaluation_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/ci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ci Evaluation
         * @description CI/CD 回归评估
         *
         *     使用金标准测试集评估，返回是否通过阈值。
         *     阈值由 RAGAS_MIN_THRESHOLD 配置控制。
         */
        post: operations["ci_evaluation_api_v1_evaluation_ci_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation History
         * @description 查看评估历史记录
         */
        get: operations["get_evaluation_history_api_v1_evaluation_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Runs
         * @description 对比两次评估的分数差异
         */
        get: operations["compare_runs_api_v1_evaluation_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description JWT 无状态：客户端丢弃 Token 即可；预留服务端黑名单可在此扩展。
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_projects__project_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_projects__project_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Member Role */
        patch: operations["update_member_role_api_v1_projects__project_id__members__user_id__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Api V1
         * @description 与 `/health` 相同，便于前端统一使用 `/api/v1` 前缀。
         */
        get: operations["health_api_v1_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_invoke_skill_api_v1_search_skill__skill_name__post */
        Body_invoke_skill_api_v1_search_skill__skill_name__post: {
            request: components["schemas"]["SearchRequest"];
            /** Doc Ids */
            doc_ids?: string[] | null;
            /** Params */
            params?: Record<string, never> | null;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Upload By */
            upload_by?: string | null;
            /**
             * Stage
             * @default 执行阶段
             */
            stage: string;
        };
        /**
         * CitationSource
         * @description 引用溯源元数据
         */
        CitationSource: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Doc Name */
            doc_name: string;
            /** Doc Type */
            doc_type?: string | null;
            /** Md Path */
            md_path: string;
            /** Section Path */
            section_path: string;
            /** Section Title */
            section_title?: string | null;
            /** Source Path */
            source_path: string;
            /** Source Format */
            source_format: string;
            /** Page Num */
            page_num?: number | null;
            /** Sheet Name */
            sheet_name?: string | null;
            /** Timestamp Sec */
            timestamp_sec?: number | null;
            /** Content Snippet */
            content_snippet: string;
            /** Highlight Text */
            highlight_text?: string | null;
            /** Checksum */
            checksum?: string | null;
            /** Upload By */
            upload_by?: string | null;
            /** Upload At */
            upload_at?: string | null;
            /** Relevance Score */
            relevance_score: number;
            retrieval_method: components["schemas"]["RetrievalMethod"];
        };
        /**
         * ConversionStatus
         * @enum {string}
         */
        ConversionStatus: "pending" | "processing" | "completed" | "failed";
        /** DocumentInfo */
        DocumentInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Original Filename */
            original_filename: string;
            /** Source Format */
            source_format: string;
            conversion_status: components["schemas"]["ConversionStatus"];
            /** Conversion Error */
            conversion_error?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** File Size Bytes */
            file_size_bytes?: number | null;
            /** Checksum */
            checksum?: string | null;
            /**
             * Upload By
             * Format: uuid
             */
            upload_by: string;
            /**
             * Upload At
             * Format: date-time
             */
            upload_at: string;
            /** Converted At */
            converted_at?: string | null;
        };
        /**
         * DocumentOutlineNode
         * @description 文档目录树节点
         */
        DocumentOutlineNode: {
            /** Section Path */
            section_path: string;
            /** Title */
            title: string | null;
            /** Level */
            level: number;
            /** Page Num */
            page_num?: number | null;
            /**
             * Has Children
             * @default false
             */
            has_children: boolean;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["DocumentOutlineNode"][];
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Source Format */
            source_format: string;
            /** Checksum */
            checksum: string;
            status: components["schemas"]["ConversionStatus"];
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MCPListResponse
         * @description list_documents 响应
         */
        MCPListResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Total Count */
            total_count: number;
            /** Documents */
            documents: components["schemas"]["DocumentInfo"][];
        };
        /**
         * MCPOutlineResponse
         * @description get_document_outline 响应
         */
        MCPOutlineResponse: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Doc Name */
            doc_name: string;
            /** Outline */
            outline: components["schemas"]["DocumentOutlineNode"][];
        };
        /**
         * MCPReadResponse
         * @description read_section 响应
         */
        MCPReadResponse: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Section Path */
            section_path: string;
            /** Section Title */
            section_title: string | null;
            /** Content */
            content: string;
            /** Page Num */
            page_num?: number | null;
            citation: components["schemas"]["CitationSource"];
        };
        /**
         * MCPSearchResponse
         * @description search_sections 响应
         */
        MCPSearchResponse: {
            /** Query */
            query: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Total Hits */
            total_hits: number;
            /** Sections */
            sections: components["schemas"]["SectionInfo"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Phase */
            phase: string;
            health: components["schemas"]["ProjectHealthMetrics"];
            /**
             * Timeline
             * @default []
             */
            timeline: Record<string, never>[];
            /** Last Report Excerpt */
            last_report_excerpt?: string | null;
            onboarding: components["schemas"]["ProjectOnboarding"];
        };
        /** ProjectHealthMetrics */
        ProjectHealthMetrics: {
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Risk
             * @default 0
             */
            risk: number;
            /**
             * Quality
             * @default 0
             */
            quality: number;
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Phase */
            phase: string;
            /** Member Count */
            member_count: number;
            /** Document Count */
            document_count: number;
            /** Health */
            health: string;
            /** Last Update At */
            last_update_at: string | null;
            /** Pending Summary */
            pending_summary: string;
        };
        /**
         * ProjectListResponse
         * @description 项目列表分页（与筛选条件一致的 total）
         */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ProjectMemberAdd */
        ProjectMemberAdd: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Role
             * @default viewer
             */
            role: string;
        };
        /** ProjectMemberItem */
        ProjectMemberItem: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** ProjectMemberRoleUpdate */
        ProjectMemberRoleUpdate: {
            /** Role */
            role: string;
        };
        /** ProjectOnboarding */
        ProjectOnboarding: {
            /** Has Uploaded Doc */
            has_uploaded_doc: boolean;
            /** Has Indexed Knowledge */
            has_indexed_knowledge: boolean;
            /** Has Tried Qa */
            has_tried_qa: boolean;
            /** Has Viewed Risk Or Report */
            has_viewed_risk_or_report: boolean;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Stage */
            stage?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RetrievalMethod
         * @enum {string}
         */
        RetrievalMethod: "vector" | "fulltext" | "mcp_tool";
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /**
         * SearchResponse
         * @description 检索响应
         */
        SearchResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationSource"][];
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Retrieval Method */
            retrieval_method: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * SearchResult
         * @description 单条检索结果
         */
        SearchResult: {
            /** Content */
            content: string;
            citation: components["schemas"]["CitationSource"];
            /** Score */
            score: number;
        };
        /** SectionInfo */
        SectionInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Section Path */
            section_path: string;
            /** Section Title */
            section_title?: string | null;
            /** Level */
            level: number;
            /** Content */
            content: string;
            /** Page Num */
            page_num?: number | null;
            /** Sheet Name */
            sheet_name?: string | null;
            /** Timestamp Sec */
            timestamp_sec?: number | null;
            /** Char Count */
            char_count?: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Refresh Expires In */
            refresh_expires_in?: number | null;
            user: components["schemas"]["UserPublic"];
        };
        /**
         * UserPublic
         * @description 与前端 auth-context 对齐的 User
         */
        UserPublic: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_list__project_id__get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_markdown_api_v1_documents__doc_id__markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stream_api_v1_search_stream_get: {
        parameters: {
            query: {
                query: string;
                project_id: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoke_skill_api_v1_search_skill__skill_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_invoke_skill_api_v1_search_skill__skill_name__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_search_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mcp_list_documents_api_v1_mcp_list_documents__project_id__get: {
        parameters: {
            query?: {
                /** @description 状态过滤 */
                status?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_get_outline_api_v1_mcp_get_outline__doc_id__get: {
        parameters: {
            query: {
                /** @description 项目 ID */
                project_id: string;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPOutlineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_search_sections_api_v1_mcp_search_sections_get: {
        parameters: {
            query: {
                /** @description 搜索关键词 */
                query: string;
                /** @description 项目 ID */
                project_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_read_section_api_v1_mcp_read_section__doc_id__get: {
        parameters: {
            query: {
                /** @description 章节路径 */
                section_path: string;
                /** @description 项目 ID */
                project_id: string;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entity_types_api_v1_graph_entities__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbors_api_v1_graph_neighbors_get: {
        parameters: {
            query: {
                entity_name: string;
                project_id: string;
                depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_query_api_v1_graph_query_get: {
        parameters: {
            query: {
                query: string;
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_extraction_api_v1_graph_extract__doc_id__post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_graph_api_v1_graph_project__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_evaluation_api_v1_evaluation_trigger_post: {
        parameters: {
            query?: {
                project_id?: string | null;
                hours?: number;
                max_samples?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ci_evaluation_api_v1_evaluation_ci_post: {
        parameters: {
            query?: {
                golden_path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_history_api_v1_evaluation_history_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_v1_evaluation_compare_get: {
        parameters: {
            query: {
                /** @description 基线 run_id */
                run_id_a: string;
                /** @description 对比 run_id */
                run_id_b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                /** @description 名称/描述模糊搜索 */
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_projects__project_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_projects__project_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_v1_projects__project_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_v1_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
